pub const INTERPRETER_WiNDOW_TITLE = "chip8-z";

pub const CHIP8_WIDTH = 64;
pub const CHIP8_HEIGHT = 32;

pub const CHIP8_SCALE_FACTOR = 10;
pub const CHIP8_SCALED_WIDTH = CHIP8_WIDTH * CHIP8_SCALE_FACTOR;
pub const CHIP8_SCALED_HEIGHT = CHIP8_HEIGHT * CHIP8_SCALE_FACTOR;

pub const CHIP8_MEMORY_SIZE = 4096;

pub const CHIP8_TOTAL_DATA_REGISTERS = 16;
pub const CHIP8_TOTAL_STACK_DEPTH = 16;

pub const CHIP8_TOTAL_KEYS = 16;
